### ISSUE TITLE
How to use TopK？

### ISSUE THREAD

**Issue by jkwebster** [mayconbordin/streaminer-storm#1]
It's a great work！But would you please tell me how to use TopK algorithm?
Thanx

**Comment by mayconbordin** [comment]
I didn't had implemented a bolt for the TopK algorithms. Take a look at [TopK](https://github.com/mayconbordin/streaminer-storm/blob/master/src/main/java/storm/streaminer/TopK.java) class.

An example of usage:

``` java
StreamSummary<String> topk = new StreamSummary<String>(100);
builder.setBolt("topK", new TopK<String>(topk, 5).setOutputFields("word", "frequency"), 12)
       .fieldsGrouping("split", new Fields("word"));
```

It is similar to the wordcount, it receives a tuple with one field: word. For every tuple received the `TopK` bolt adds it to the data structure and every 5 seconds emits the top k items.

**Comment by jkwebster** [comment]
Thx much!

# Another question,it seems that BloomFIlter result in zero,the returned value is "True",why?

 IFilter bloom = new BloomFilter(1000, 32, Hash.MURMUR_HASH);

```
    for (int i = 0; i < 100; i++) {
        String val = UUID.randomUUID().toString();
        Key k = new Key(val.getBytes());
        bloom.add(k);
        System.out.println(val + " exists? " + bloom.membershipTest(k));
    }
```

# 

514bc09a-92fe-415a-ba9c-81b3421eccf4 exists? true
3376dc0c-187a-4289-8a36-6641c9ac5aff exists? true
636fedb4-4767-44b8-97fa-acf73603af25 exists? true
59c8aff2-2cac-4657-9f49-57b4d2c49f31 exists? true
81eb8468-61f2-4b76-8057-f0d0e86a376d exists? true
72f406de-1288-47ca-b5ff-c805b18c0094 exists? true
0419131c-b5a3-4b13-a674-fb74fed2c458 exists? true
ecb19369-0e4b-4593-a697-ad769c71246b exists? true
a7ba7d66-a57c-4683-ad67-a6c0c0c214c4 exists? true
5582f34e-2e19-429e-809c-321757c650a4 exists? true
27700def-b4a3-41cf-932a-baeaf5c9fac3 exists? true
a869e485-b5dc-4565-bf70-0d259f449fb6 exists? true
78a69c51-980e-4811-aca7-56e2b18cf460 exists? true
............

**Comment by mayconbordin** [comment]
In this code you are creating a random key, adding it to the bloom filter and asking the bloom filter if the key is stored in the data structure, so it is supposed to be always true.

In a more real scenario you could have a cache to store some data by their ID, and then, before retrieving the data from a database, check in the cache if the data is there. Under the hood the cache could use a bloom filter in order to know if an ID is there.

**Comment by jkwebster** [comment]
For TopK  algorithm,if I use LocalCluster mode,and set conf.setMaxTaskParallelism(3), then I got 3 different TopK ranking,but you know I only really want the Unique TopK result.In order to solve this problem,do I have to set setMaxTaskParallelism=1?
